[package]
name = "smwasmgo_rustlib"
version = "0.0.1"
edition = "2018"

[dependencies]
once_cell = "1.18"
lazy_static = "1.4.0"
json = "0.12.4"
libc = "0.2"

smcore = "0.1.3"
smdton = "0.1.2"
smloadwasm = "0.1.3"
smsys = "0.1.0"

[lib]
crate-type = ["cdylib"]
